### ISSUE TITLE
nhostreact0.14.2 breaks my Expo React Native (Hermes) app

### ISSUE THREAD

**Issue by comontes** [nhost/nhost#1160]
After upgrading from @nhost/react@0.14.1 to @nhost/react@0.14.2 my Expo React Native(Hermes) app is broken with the following error:

<img width="1219" alt="Screenshot_2022-11-20_at_19_40_13-2" src="https://user-images.githubusercontent.com/1701089/203102964-d0ebb7ea-0a30-4331-b4d5-7138d91589c1.png">

```
› Metro waiting on com.name.app://expo-development-client/?url=http%3A%2F%2F192.168.0.121%3A8081
› Scan the QR code above with Expo Go (Android) or the Camera app (iOS)

› Press a │ open Android
› Press i │ open iOS simulator
› Press w │ open web

› Press j │ open debugger
› Press r │ reload app
› Press m │ toggle menu

› Press ? │ show all commands

Logs for your project will appear below. Press Ctrl+C to exit.
Android Bundling complete 3659ms
Error: ENOENT: no such file or directory, open '/Users/username/ts-lingo/unknown'
    at Object.openSync (node:fs:599:3)
    at Object.readFileSync (node:fs:467:35)
    at getCodeFrame (/Users/username/ts-lingo/node_modules/metro/src/Server.js:1028:18)
    at Server._symbolicate (/Users/username/ts-lingo/node_modules/metro/src/Server.js:1101:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Server._processRequest (/Users/username/ts-lingo/node_modules/metro/src/Server.js:458:7) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/username/ts-lingo/unknown'
}
 ERROR  SyntaxError: 159790:11:Invalid regular expression: Quantifier has nothing to repeat, js engine: hermes
 ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
 ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
```

**Comment by plmercereau** [comment]
Maybe related
https://github.com/facebook/hermes/issues/46

**Comment by pkreipke** [comment]
Link to OG [Discord thread](https://discord.com/channels/552499021260914688/1044037452102381618/1044037452102381618) ...

**Comment by comontes** [comment]
"Invalid regular expression: Quantifier has nothing to repeat, js engine: hermes" is solved by the @babel/plugin-transform-named-capturing-groups-regex Babel plugin.

Step 1: 
yarn add --dev @babel/plugin-transform-named-capturing-groups-regex

Step 2:
Add plugin in babel.config.js
Mine looks like this:
<img width="574" alt="Screenshot 2022-11-21 at 18 30 31" src="https://user-images.githubusercontent.com/1701089/203162032-c932b724-33a5-4b4a-bd07-aa43a5e178c5.png">

Step 3:
restart the development server and clear the bundler cache with: npx expo start --clear, or in my case npx expo start --dev-client --clear (I'm using dev-client)

Result:
<img width="797" alt="Screenshot 2022-11-21 at 18 28 10" src="https://user-images.githubusercontent.com/1701089/203162364-def6c05a-460f-4a8e-b4a8-c982e44a7f3b.png">

Sadly, there are still errors caused by the upgrade of the Nhost React library v 0.14.2

**Comment by comontes** [comment]
"ERROR  TypeError: Restricted in strict mode, js engine: hermes" seems to come from the use of axios@^1.1.3 by Nhost. 
See Axios bug here: https://github.com/axios/axios/issues/4998

**Comment by plmercereau** [comment]
We're getting more and more tired of Axios at Nhost, maybe it's time to plan our project related to cross-fetch, @nunopato 
About the regexp we'll look for a way to adapt it to please Hermes - from what i gather he's not the kind of god you're messing with 😬

**Comment by plmercereau** [comment]
@seyaobey-dev could you try the [solution suggested by @comontes](https://github.com/nhost/nhost/issues/1160#issuecomment-1322678644)?

**Comment by seyaobey-dev** [comment]
@plmercereau thanks for the suggestion. The build past with the use of `@babel/plugin-transform-named-capturing-groups-regex` babel plugin.

**Comment by Svarto** [comment]
Ran into same issue, the Babel transformer works solution works for now
