### ISSUE TITLE
NhostClient not working in react native cli generated project

### ISSUE THREAD

**Issue by coyksdev** [nhost/nhost#1340]
I created a project using react native cli. I was able to run the app initially but when I added the code that instantiates NhostClient the app breaks. Tried this [solutions](https://github.com/nhost/nhost/issues/1160) but it only works in react native expo.

```
// instantiate NhostClient
const nhost = new NhostClient({
  subdomain: ....
  region: ...,
});

```

```
// package.json
{
  "name": "Booker",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint . --ext .js,.jsx,.ts,.tsx"
  },
  "dependencies": {
    "@nhost/react": "^0.15.2",
    "graphql": "^16.6.0",
    "react": "18.1.0",
    "react-native": "0.70.6"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/plugin-transform-named-capturing-groups-regex": "^7.20.5",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "@tsconfig/react-native": "^2.0.2",
    "@types/jest": "^26.0.23",
    "@types/react": "^18.0.21",
    "@types/react-native": "^0.70.6",
    "@types/react-test-renderer": "^18.0.0",
    "@typescript-eslint/eslint-plugin": "^5.37.0",
    "@typescript-eslint/parser": "^5.37.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.32.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "0.72.3",
    "react-test-renderer": "18.1.0",
    "typescript": "^4.8.3"
  },
  "jest": {
    "preset": "react-native",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ]
  }
}
```

**iOS error logs**
```
 ERROR  SyntaxError: 95676:9:Invalid regular expression: Quantifier has nothing to repeat, js engine: hermes
 ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 10): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
Error: ENOENT: no such file or directory, open '/Users/gbc9720/Documents/projects/Booker/unknown'
    at Object.openSync (fs.js:498:3)
    at Object.readFileSync (fs.js:394:35)
    at getCodeFrame (/Users/gbc9720/Documents/projects/Booker/node_modules/metro/src/Server.js:1028:18)
    at Server._symbolicate (/Users/gbc9720/Documents/projects/Booker/node_modules/metro/src/Server.js:1101:22)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Server._processRequest (/Users/gbc9720/Documents/projects/Booker/node_modules/metro/src/Server.js:458:7) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/gbc9720/Documents/projects/Booker/unknown'
}
 ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 10): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
```

**Comment by coyksdev** [comment]
I update the above description. Looks like it only occurs in iOS.

**Comment by Svarto** [comment]
Did you update `babel.config.js` correctly? The proposed solution should work in react native cli as well as it transforms the offending regex at bundling time, this is not expo specific...

The solution to this on the nhost side is duplicating the solution for this issue though: https://github.com/nhost/nhost/issues/1160

**Comment by coyksdev** [comment]
@Svarto here is my babel.config.js

`module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    '@babel/plugin-transform-named-capturing-groups-regex',
    'react-native-reanimated/plugin',
  ],
};`

**Comment by Svarto** [comment]
You probably did this already, but make sure you clean cache and delete the iOS/ folder and rebuild it from scratch. The Babel plugin fixed this exact issue for me, so I'm a bit stumped...
