### ISSUE TITLE
admin role is always added regardless if allowedRoles is specified

### ISSUE THREAD

**Issue by iangabrielsanchez** [nhost/nhost#1488]
**Describe the bug**
We are logging in with linkedin using the following code:
```
function signInWithProvider(provider: string, redirectTo?: string) {
    let options: any = {
      allowedRoles: ['user', 'me'],
    };
    if (redirectTo && redirectTo !== '') {
      options.redirectTo = redirectTo;
    }

    return client.nhost.auth.signIn({
      provider: (provider as any) ?? 'linkedin',
      options,
    });
  }
```
The idea is that all users should log in with linkedin but selected users will be promoted to admin manually via the nhost dashboard.

The roles we have right now are:
 - user
 - me
 - admin
 
 However, whenever we call the said function, it either crashes the server, or creates a new user with 'admin' role checked. here are some logs that could be useful:
 
```
2023-01-09 14:06:59 | hasura-auth | ELIFECYCLE  Command failed with exit code 1.
-- | -- | --
2023-01-09 14:06:59 | hasura-auth | at async /app/dist/routes/oauth/index.js:241:31
2023-01-09 14:06:59 | hasura-auth | at processTicksAndRejections (node:internal/process/task_queues:96:5)
2023-01-09 14:06:59 | hasura-auth | at transformOauthProfile (/app/dist/routes/oauth/utils.js:40:141)
2023-01-09 14:06:59 | hasura-auth | TypeError: ((intermediate value)(intermediate value)(intermediate value) \|\| utils_1.ENV.AUTH_USER_DEFAULT_ALLOWED_ROLES).map is not a function
2023-01-09 14:06:59 | hasura-auth |  
2023-01-09 14:06:59 | hasura-auth | ^
2023-01-09 14:06:59 | hasura-auth | data: ((options === null \|\| options === void 0 ? void 0 : options.allowedRoles) \|\| utils_1.ENV.AUTH_USER_DEFAULT_ALLOWED_ROLES).map((role) => ({
2023-01-09 14:06:59 | hasura-auth | /app/dist/routes/oauth/utils.js:40

```

**To Reproduce**
1. Create a new project on app.nhost.io
2. Set up linkedin login
3. login with linkedin (vue app) using the code above

**Comment by iangabrielsanchez** [comment]
A workaround for this is to:
1. Remove the admin role in nhost UI
2. Manually add an `admin` role in the auth.roles table
3. Manually add the `admin` role with the associated user id in auth.user_roles

It fulfills the requirements for now but it would be nice if we could do this with the UI

**Comment by guicurcio** [comment]
I don't quite follow, how come does the admin role gets added regardless if it's not present in the code? Also adding a `role` in the "Allowed Roles" section of Nhost cloud should create both of the roles you mention in those columns -- though not in the Hasura metadata.

Could you give me a subdomain link so I can take a look?

**Comment by iangabrielsanchez** [comment]
Will try to reproduce when I get the chance

**Comment by iangabrielsanchez** [comment]
@szilarddoro @guicurcio I opened up a PR that would fix the error shared above.
https://github.com/nhost/hasura-auth/pull/391

**Comment by iangabrielsanchez** [comment]
I just want to clear some things out.

It all starts when you add `someRole` in the Allowed Roles.
![image](https://github.com/nhost/nhost/assets/9511946/1c21aacc-2f1a-4ac3-8994-db1ae683f7aa)

 From what I understand this sets values to the `AUTH_USER_DEFAULT_ALLOWED_ROLES` env variable.
 
Then if you try to sign up with a provider (tested with linkedin) using this code,
```
    return $nhost.auth.signIn({
      provider: (provider as any) ?? 'linkedin',
      options: {
        allowedRoles: ['user', 'me']
      },
    });
```

you get this issue:
```
2023-01-09 14:06:59 | hasura-auth | ELIFECYCLE  Command failed with exit code 1.
-- | -- | --
2023-01-09 14:06:59 | hasura-auth | at async /app/dist/routes/oauth/index.js:241:31
2023-01-09 14:06:59 | hasura-auth | at processTicksAndRejections (node:internal/process/task_queues:96:5)
2023-01-09 14:06:59 | hasura-auth | at transformOauthProfile (/app/dist/routes/oauth/utils.js:40:141)
2023-01-09 14:06:59 | hasura-auth | TypeError: ((intermediate value)(intermediate value)(intermediate value) \|\| utils_1.ENV.AUTH_USER_DEFAULT_ALLOWED_ROLES).map is not a function
2023-01-09 14:06:59 | hasura-auth |  
2023-01-09 14:06:59 | hasura-auth | ^
2023-01-09 14:06:59 | hasura-auth | data: ((options === null \|\| options === void 0 ? void 0 : options.allowedRoles) \|\| utils_1.ENV.AUTH_USER_DEFAULT_ALLOWED_ROLES).map((role) => ({
2023-01-09 14:06:59 | hasura-auth | /app/dist/routes/oauth/utils.js:40
```

I inspected the code related to this and it looks like the `options.allowedRoles` getting passed come from the query parameter during oauth and it is not transformed into the expected `string[]` type but is instead a `string`. The pull request I mentioned (https://github.com/nhost/hasura-auth/pull/391) should fix this

**Comment by szilarddoro** [comment]
Hey @iangabrielsanchez! Sorry for not getting back to you regarding this. I will find some time early next week to review your PR.
