### ISSUE TITLE
Issues with the stripe extension

### ISSUE THREAD

**Issue by edinskeja** [nhost/nhost#1578]
**Describe the bug**
I'm having issues with the stripe extension both locally and in production.

Local error
```sh
Unable to load file functions/graphql/stripe.ts as a Serverless Function
```
Production error
```sh 
{"log":"Uncaught Exception \t{\"errorType\":\"Runtime.HandlerNotFound\",\"errorMessage\":\"lambda.handler is undefined or not exported\",\"stack\":[\"Runtime.HandlerNotFound: lambda.handler is undefined or not exported\",\" at Object.UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1038:15)\",\" at async start (file:///var/runtime/index.mjs:1200:23)\",\" at async file:///var/runtime/index.mjs:1206:1\"]}","path":"/graphql/stripe","requestId":"undefined","level":"ERROR"}
```

I used the plugin in another nhost project some months ago and it was working after following the guide https://nhost.io/blog/open-source-stripe-graphql-api

This is the simple code in the `stripe.ts`
```js
import { createStripeGraphQLServer } from '@nhost/stripe-graphql-js';

const server = createStripeGraphQLServer();

export default server;
```

**To Reproduce**
1. Go to 'functions/'
2. Install latest `@nhost/stripe-graphql-js`
3. Run `nhost dev`
4. Run `nhost logs functions -f`
5. See error

**Desktop (please complete the following information):**
 - OS: MacOS 13.0.1
 - Browser Chrome

**Comment by jovermier** [comment]
This might be related to issue https://github.com/nhost/nhost/issues/1577

**Comment by antoinecaputo** [comment]
Same issue with  @nhost/stripe-graphql-js v1.0.2 running on nhost/functions:0.1.8 docker image

**Comment by antoinecaputo** [comment]
Can you please detail how have you initiated the YogaServerInstance

**Comment by tawsbob** [comment]
Same issue here, trying to fix as @jogri

**Comment by dbarrosop** [comment]
I am afraid we can't reproduce so I'd ask if someone could share a repository with steps to reproduce. Thanks!

**Comment by tawsbob** [comment]
@dbarrosop  I'm Using MAC M1 PRO with Ventura 14.4.1

1) I just follow [this step](https://docs.nhost.io/cli/local-development) to have my local environment
2) try to include stripe remote schema to following [this steps in docs](https://docs.nhost.io/graphql/remote-schemas/stripe).
3) Install deps and so on
4) nhost up
5) nhost logs functions  -f

```bash
Unable to load file functions/stripe/graphql.js as a Serverless Function
```
<img width="753" alt="Screenshot 2023-07-25 at 11 21 38" src="https://github.com/nhost/nhost/assets/8184351/cbfca15b-6efb-420c-894a-d3031c7fcd95">

**Comment by tawsbob** [comment]
From what I saw the serveless functions require a handler function exporte as default in js|ts file, the createStripeGraphQLServer exported on '@nhost/stripe-graphql-js' module use createServer from node:http to wrap the yoga.

**Comment by xecutors-io** [comment]
facing the same issue on a fresh setup 
2023-07-28 22:53:29 thp-functions-1  | Unable to load file functions/graphql/stripe.ts as a Serverless Function

**Comment by ssteiger** [comment]
I'm having the same issue:

Error.
```bash
Unable to load file functions/graphql/stripe.ts as a Serverless Function
```

**Comment by dbarrosop** [comment]
I nobody beats us to it we will be looking into this during August.

**Comment by AlexisFilia** [comment]
Hello,
Any news on this topic ?

**Comment by darrow97** [comment]
@AlexisFilia I don't have a progress report on a fix for this, but this is a temporary fix my team and I figured out yesterday and this morning. We sought to out a fix that did not change the nhost code base. Here's what we found:

Since the serverless function is expecting a handler/listener (ie `handler(req, res)`), we looked for a handler/listener within the server object returned from `createStripeGraphQLServer()` and found it. Here is what our fix looks like:
```
import { createStripeGraphQLServer } from '@nhost/stripe-graphql-js';

/** Original approach
*
* export default server;
*
* const server = createStripeGraphQLServer();
*/

/** New approach / Fix until nhost releases official fix */
const server = createStripeGraphQLServer();
  
export default server._events.request;
```

**Comment by darrow97** [comment]
Where might one find this example? The docs look the same as before

**Comment by dbarrosop** [comment]
I don't think anything changes, you just need to update the package. @onehassan could you confirm?

**Comment by onehassan** [comment]
It's the same as before. I just wanted to give a heads up that if you've used a workaround you should revert to how it's described in the docs

**Comment by darrow97** [comment]
excellent. Thank you @onehassan !
