### ISSUE TITLE
Config file cant be loaded

### ISSUE THREAD

**Issue by RG7279805** [nhost/nhost#1634]
**Describe the bug**
Config file cant be loaded

**To Reproduce**
1. npm install -g pnpm
2. clone the repo
3. ``` pnpm install ```
4.  ```pnpm dev```

**Expected behavior**
all the dev servers should start up instead if i get errors 
```
PS C:\Users\RG\Desktop\projects\nhost> pnpm dev

> nhost-root@0.0.0 dev C:\Users\RG\Desktop\projects\nhost
> turbo run dev --filter=!@nhost/dashboard --filter=!@nhost/docs --filter=!@nhost-examples/* --filter=!@nhost/docgen --no-deps --include-dependencies

 WARNING  failed to contact turbod. Continuing in standalone mode: connection to turbo daemon process failed. Please ensure the following:
        - the process identified by the pid in the file at C:\Users\RG\AppData\Local\Temp\turbod\f11ff9654fba8e4d\turbod.pid is not running, and remove C:\Users\RG\AppData\Local\Temp\turbod\f11ff9654fba8e4d\turbod.pid
        - check the logs at C:\Users\RG\AppData\Local\turborepo\logs\f11ff9654fba8e4d-nhost.log
        - the unix domain socket at C:\Users\RG\AppData\Local\Temp\turbod\f11ff9654fba8e4d\turbod.sock has been removed
        You can also run without the daemon process by passing --no-daemon
• Packages in scope: @nhost/apollo, @nhost/google-translation, @nhost/hasura-auth-js, @nhost/hasura-storage-js, @nhost/nextjs, @nhost/nhost-js, @nhost/react, @nhost/react-apollo, @nhost/react-urql, @nhost/stripe-graphql-js, @nhost/sync-versions, @nhost/vue
• Running dev in 12 packages
• Remote caching disabled
@nhost/react-apollo:dev: cache bypass, force executing 75f58a4c1aa618c1
@nhost/apollo:dev: cache bypass, force executing 8e6de965fa2ab8ea
@nhost/stripe-graphql-js:dev: cache bypass, force executing a4aa4b4f51bf7201
@nhost/hasura-auth-js:dev: cache bypass, force executing 17f31aaa189679e2
@nhost/google-translation:dev: cache bypass, force executing 2636f566d9689062
@nhost/hasura-storage-js:dev: cache bypass, force executing b53160266e3ea61a
@nhost/react:dev: cache bypass, force executing da298d66b797ec6b
@nhost/vue:dev: cache bypass, force executing a9e10a6cd4b7f439
@nhost/nhost-js:dev: cache bypass, force executing bdaa488e7dd5591c
@nhost/nextjs:dev: cache bypass, force executing f6c2d4fb78bdbf37
@nhost/hasura-auth-js:dev:
@nhost/hasura-auth-js:dev: > @nhost/hasura-auth-js@1.12.4 dev C:\Users\RG\Desktop\projects\nhost\packages\hasura-auth-js
@nhost/hasura-auth-js:dev: > vite build --config ./vite.dev.config.js
@nhost/hasura-auth-js:dev:
@nhost/hasura-storage-js:dev:
@nhost/hasura-storage-js:dev: > @nhost/hasura-storage-js@1.13.2 dev C:\Users\RG\Desktop\projects\nhost\packages\hasura-storage-js
@nhost/hasura-storage-js:dev: > vite build --config ../../config/vite.lib.dev.config.js
@nhost/hasura-storage-js:dev:
@nhost/apollo:dev:
@nhost/apollo:dev: > @nhost/apollo@4.13.4 dev C:\Users\RG\Desktop\projects\nhost\integrations\apollo
@nhost/apollo:dev: > vite build --config ../../config/vite.lib.dev.config.js
@nhost/apollo:dev:
@nhost/stripe-graphql-js:dev:
@nhost/stripe-graphql-js:dev: > @nhost/stripe-graphql-js@1.0.1 dev C:\Users\RG\Desktop\projects\nhost\integrations\stripe-graphql-js
@nhost/stripe-graphql-js:dev: > NODE_ENV=development ts-node-dev -r dotenv/config dev/server.ts
@nhost/stripe-graphql-js:dev:
@nhost/google-translation:dev:
@nhost/google-translation:dev: > @nhost/google-translation@0.0.2 dev C:\Users\RG\Desktop\projects\nhost\integrations\google-translation
@nhost/google-translation:dev: > vite build --config ../../config/vite.lib.dev.config.js
@nhost/google-translation:dev:
@nhost/vue:dev:
@nhost/vue:dev: > @nhost/vue@1.13.5 dev C:\Users\RG\Desktop\projects\nhost\packages\vue
@nhost/vue:dev: > vite build --config ../../config/vite.vue.dev.config.js
@nhost/vue:dev:
@nhost/react-apollo:dev:
@nhost/react-apollo:dev: > @nhost/react-apollo@4.13.5 dev C:\Users\RG\Desktop\projects\nhost\integrations\react-apollo
@nhost/react-apollo:dev: > vite build --config ../../config/vite.react.dev.config.js
@nhost/react-apollo:dev:
@nhost/nhost-js:dev:
@nhost/nhost-js:dev: > @nhost/nhost-js@1.13.4 dev C:\Users\RG\Desktop\projects\nhost\packages\nhost-js
@nhost/nhost-js:dev: > vite build --config ../../config/vite.lib.dev.config.js
@nhost/nhost-js:dev:
@nhost/nextjs:dev:
@nhost/nextjs:dev: > @nhost/nextjs@1.13.5 dev C:\Users\RG\Desktop\projects\nhost\packages\nextjs
@nhost/nextjs:dev: > vite build --config ../../config/vite.react.dev.config.js
@nhost/nextjs:dev:
@nhost/react:dev:
@nhost/react:dev: > @nhost/react@1.13.5 dev C:\Users\RG\Desktop\projects\nhost\packages\react
@nhost/react:dev: > vite build --config ../../config/vite.react.dev.config.js
@nhost/react:dev:
@nhost/stripe-graphql-js:dev: [INFO] 12:25:03 ts-node-dev ver. 2.0.0 (using ts-node ver. 10.9.1, typescript ver. 4.7.4)
@nhost/google-translation:dev: failed to load config from C:\Users\RG\Desktop\projects\nhost\config\vite.lib.dev.config.js
@nhost/google-translation:dev: error during build:
@nhost/google-translation:dev: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
@nhost/google-translation:dev:     at new NodeError (node:internal/errors:387:5)
@nhost/google-translation:dev:     at validateString (node:internal/validators:162:11)
@nhost/google-translation:dev:     at Object.join (node:path:429:7)
@nhost/google-translation:dev:     at Object.<anonymous> (C:\Users\RG\Desktop\projects\nhost\config\vite.lib.dev.config.js:41:39)
@nhost/google-translation:dev:     at Module._compile (node:internal/modules/cjs/loader:1191:14)
@nhost/google-translation:dev:     at Object._require.extensions.<computed> [as .js] (file:///C:/Users/RG/Desktop/projects/nhost/node_modules/.pnpm/vite@4.0.2_@types+node@16.18.11/node_modules/vite/dist/node/chunks/dep-6305614c.js:63130:24)
@nhost/google-translation:dev:     at Module.load (node:internal/modules/cjs/loader:1069:32)
@nhost/google-translation:dev:     at Function.Module._load (node:internal/modules/cjs/loader:904:12)
@nhost/google-translation:dev:     at Module.require (node:internal/modules/cjs/loader:1093:19)
@nhost/google-translation:dev:     at require (node:internal/modules/cjs/helpers:108:18)
@nhost/react-apollo:dev: failed to load config from C:\Users\RG\Desktop\projects\nhost\config\vite.react.dev.config.js
@nhost/react-apollo:dev: error during build:
@nhost/react-apollo:dev: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
@nhost/react-apollo:dev:     at new NodeError (node:internal/errors:387:5)
@nhost/react-apollo:dev:     at validateString (node:internal/validators:162:11)
@nhost/react-apollo:dev:     at Object.join (node:path:429:7)
@nhost/react-apollo:dev:     at Object.<anonymous> (C:\Users\RG\Desktop\projects\nhost\config\vite.react.dev.config.js:45:39)
@nhost/react-apollo:dev:     at Module._compile (node:internal/modules/cjs/loader:1191:14)
@nhost/react-apollo:dev:     at Object._require.extensions.<computed> [as .js] (file:///C:/Users/RG/Desktop/projects/nhost/node_modules/.pnpm/vite@4.0.2_@types+node@16.18.11/node_modules/vite/dist/node/chunks/dep-6305614c.js:63130:24)
@nhost/react-apollo:dev:  ELIFECYCLE  Command failed with exit code 1.
@nhost/react:dev: failed to load config from C:\Users\RG\Desktop\projects\nhost\config\vite.react.dev.config.js
@nhost/react:dev: error during build:
@nhost/react:dev: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
@nhost/react:dev:     at new NodeError (node:internal/errors:387:5)
@nhost/react:dev:     at validateString (node:internal/validators:162:11)
@nhost/react:dev:     at Object.join (node:path:429:7)
@nhost/react:dev:     at Object.<anonymous> (C:\Users\RG\Desktop\projects\nhost\config\vite.react.dev.config.js:45:39)
@nhost/react:dev:     at Module._compile (node:internal/modules/cjs/loader:1191:14)
@nhost/react:dev:     at Object._require.extensions.<computed> [as .js] (file:///C:/Users/RG/Desktop/projects/nhost/node_modules/.pnpm/vite@4.0.2_@types+node@16.18.11/node_modules/vite/dist/node/chunks/dep-6305614c.js:63130:24)
@nhost/react:dev:     at Module.load (node:internal/modules/cjs/loader:1069:32)
@nhost/react:dev:     at Function.Module._load (node:internal/modules/cjs/loader:904:12)
@nhost/react:dev:     at Module.require (node:internal/modules/cjs/loader:1093:19)
@nhost/react:dev:     at require (node:internal/modules/cjs/helpers:108:18)
@nhost/react-apollo:dev:     at Module.load (node:internal/modules/cjs/loader:1069:32)
@nhost/react-apollo:dev:     at Function.Module._load (node:internal/modules/cjs/loader:904:12)
@nhost/react-apollo:dev:     at Module.require (node:internal/modules/cjs/loader:1093:19)
@nhost/react-apollo:dev:     at require (node:internal/modules/cjs/helpers:108:18)
@nhost/apollo:dev: failed to load config from C:\Users\RG\Desktop\projects\nhost\config\vite.lib.dev.config.js
@nhost/apollo:dev: error during build:
@nhost/apollo:dev: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
@nhost/apollo:dev:  ELIFECYCLE  Command failed with exit code 1.
@nhost/google-translation:dev:  ELIFECYCLE  Command failed with exit code 1.
@nhost/hasura-auth-js:dev: failed to load config from C:\Users\RG\Desktop\projects\nhost\packages\hasura-auth-js\vite.dev.config.js
@nhost/hasura-auth-js:dev: error during build:
@nhost/hasura-auth-js:dev:  ELIFECYCLE  Command failed with exit code 1.
@nhost/hasura-storage-js:dev: failed to load config from C:\Users\RG\Desktop\projects\nhost\config\vite.lib.dev.config.js
@nhost/hasura-storage-js:dev: error during build:
@nhost/hasura-storage-js:dev: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
@nhost/nhost-js:dev: failed to load config from C:\Users\RG\Desktop\projects\nhost\config\vite.lib.dev.config.js
@nhost/nhost-js:dev: error during build:
@nhost/nhost-js:dev:  ELIFECYCLE  Command failed with exit code 1.
@nhost/vue:dev: failed to load config from C:\Users\RG\Desktop\projects\nhost\config\vite.vue.dev.config.js
@nhost/vue:dev: error during build:
@nhost/vue:dev:  ELIFECYCLE  Command failed with exit code 1.
@nhost/vue:dev: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
@nhost/vue:dev:     at new NodeError (node:internal/errors:387:5)
@nhost/vue:dev:     at validateString (node:internal/validators:162:11)
@nhost/vue:dev:     at Object.join (node:path:429:7)
@nhost/vue:dev:     at Object.<anonymous> (C:\Users\RG\Desktop\projects\nhost\config\vite.vue.dev.config.js:45:39)
@nhost/vue:dev:     at Module._compile (node:internal/modules/cjs/loader:1191:14)
@nhost/vue:dev:     at Object._require.extensions.<computed> [as .js] (file:///C:/Users/RG/Desktop/projects/nhost/node_modules/.pnpm/vite@4.0.2_@types+node@16.18.11/node_modules/vite/dist/node/chunks/dep-6305614c.js:63130:24)
@nhost/vue:dev:     at Module.load (node:internal/modules/cjs/loader:1069:32)
@nhost/vue:dev:     at Function.Module._load (node:internal/modules/cjs/loader:904:12)
@nhost/vue:dev:     at Module.require (node:internal/modules/cjs/loader:1093:19)
@nhost/vue:dev:     at require (node:internal/modules/cjs/helpers:108:18)
@nhost/hasura-storage-js:dev:  ELIFECYCLE  Command failed with exit code 1.
@nhost/nextjs:dev: failed to load config from C:\Users\RG\Desktop\projects\nhost\config\vite.react.dev.config.js
@nhost/apollo:dev:     at new NodeError (node:internal/errors:387:5)
@nhost/apollo:dev:     at validateString (node:internal/validators:162:11)
@nhost/apollo:dev:     at Object.join (node:path:429:7)
@nhost/apollo:dev:     at Object.<anonymous> (C:\Users\RG\Desktop\projects\nhost\config\vite.lib.dev.config.js:41:39)
@nhost/apollo:dev:     at Module._compile (node:internal/modules/cjs/loader:1191:14)
@nhost/apollo:dev:     at Object._require.extensions.<computed> [as .js] (file:///C:/Users/RG/Desktop/projects/nhost/node_modules/.pnpm/vite@4.0.2_@types+node@16.18.11/node_modules/vite/dist/node/chunks/dep-6305614c.js:63130:24)
@nhost/apollo:dev:     at Module.load (node:internal/modules/cjs/loader:1069:32)
@nhost/apollo:dev:     at Function.Module._load (node:internal/modules/cjs/loader:904:12)
@nhost/apollo:dev:     at Module.require (node:internal/modules/cjs/loader:1093:19)
@nhost/apollo:dev:     at require (node:internal/modules/cjs/helpers:108:18)
@nhost/nextjs:dev: error during build:
@nhost/nextjs:dev:  ELIFECYCLE  Command failed with exit code 1.
@nhost/hasura-auth-js:dev: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
@nhost/hasura-auth-js:dev:     at new NodeError (node:internal/errors:387:5)
@nhost/react-apollo:dev: ERROR: command finished with error: command (C:\Users\RG\Desktop\projects\nhost\integrations\react-apollo) pnpm run dev exited (1)@nhost/hasura-auth-js:dev:     at validateString (node:internal/validators:162:11)

@nhost/hasura-auth-js:dev:     at Object.join (node:path:429:7)
@nhost/hasura-auth-js:dev:     at Object.<anonymous> (C:\Users\RG\Desktop\projects\nhost\packages\hasura-auth-js\vite.dev.config.js:45:39)
@nhost/hasura-auth-js:dev:     at Module._compile (node:internal/modules/cjs/loader:1191:14)
@nhost/hasura-auth-js:dev:     at Object._require.extensions.<computed> [as .js] (file:///C:/Users/RG/Desktop/projects/nhost/node_modules/.pnpm/vite@4.0.2_@types+node@16.18.11/node_modules/vite/dist/node/chunks/dep-6305614c.js:63130:24)
@nhost/nhost-js:dev: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
@nhost/nhost-js:dev:     at new NodeError (node:internal/errors:387:5)
@nhost/nhost-js:dev:     at validateString (node:internal/validators:162:11)
@nhost/nhost-js:dev:     at Object.join (node:path:429:7)
@nhost/nhost-js:dev:     at Object.<anonymous> (C:\Users\RG\Desktop\projects\nhost\config\vite.lib.dev.config.js:41:39)
@nhost/nhost-js:dev:     at Module._compile (node:internal/modules/cjs/loader:1191:14)
@nhost/nhost-js:dev:     at Object._require.extensions.<computed> [as .js] (file:///C:/Users/RG/Desktop/projects/nhost/node_modules/.pnpm/vite@4.0.2_@types+node@16.18.11/node_modules/vite/dist/node/chunks/dep-6305614c.js:63130:24)
@nhost/nhost-js:dev:     at Module.load (node:internal/modules/cjs/loader:1069:32)
@nhost/nhost-js:dev:     at Function.Module._load (node:internal/modules/cjs/loader:904:12)
@nhost/nhost-js:dev:     at Module.require (node:internal/modules/cjs/loader:1093:19)
@nhost/nhost-js:dev:     at require (node:internal/modules/cjs/helpers:108:18)
@nhost/nextjs:dev: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
@nhost/nextjs:dev:     at new NodeError (node:internal/errors:387:5)
@nhost/nextjs:dev:     at validateString (node:internal/validators:162:11)
@nhost/nextjs:dev:     at Object.join (node:path:429:7)
@nhost/nextjs:dev:     at Object.<anonymous> (C:\Users\RG\Desktop\projects\nhost\config\vite.react.dev.config.js:45:39)
@nhost/nextjs:dev:     at Module._compile (node:internal/modules/cjs/loader:1191:14)
@nhost/nextjs:dev:     at Object._require.extensions.<computed> [as .js] (file:///C:/Users/RG/Desktop/projects/nhost/node_modules/.pnpm/vite@4.0.2_@types+node@16.18.11/node_modules/vite/dist/node/chunks/dep-6305614c.js:63130:24)
@nhost/nextjs:dev:     at Module.load (node:internal/modules/cjs/loader:1069:32)
@nhost/nextjs:dev:     at Function.Module._load (node:internal/modules/cjs/loader:904:12)
@nhost/nextjs:dev:     at Module.require (node:internal/modules/cjs/loader:1093:19)
@nhost/nextjs:dev:     at require (node:internal/modules/cjs/helpers:108:18)
@nhost/react-urql:dev: cache bypass, force executing 8ec43441e5a7bc94
@nhost/react:dev:  ELIFECYCLE  Command failed with exit code 1.
@nhost/hasura-storage-js:dev:     at validateString (node:internal/validators:162:11)
@nhost/hasura-storage-js:dev:     at Object.join (node:path:429:7)
@nhost/hasura-storage-js:dev:     at Object.<anonymous> (C:\Users\RG\Desktop\projects\nhost\config\vite.lib.dev.config.js:41:39)
@nhost/hasura-storage-js:dev:     at Module._compile (node:internal/modules/cjs/loader:1191:14)
@nhost/hasura-storage-js:dev:     at Object._require.extensions.<computed> [as .js] (file:///C:/Users/RG/Desktop/projects/nhost/node_modules/.pnpm/vite@4.0.2_@types+node@16.18.11/node_modules/vite/dist/node/chunks/dep-6305614c.js:63130:24)
@nhost/hasura-storage-js:dev:     at Module.load (node:internal/modules/cjs/loader:1069:32)
@nhost/hasura-storage-js:dev:     at Function.Module._load (node:internal/modules/cjs/loader:904:12)
@nhost/hasura-storage-js:dev:     at Module.require (node:internal/modules/cjs/loader:1093:19)
@nhost/hasura-storage-js:dev:     at require (node:internal/modules/cjs/helpers:108:18)
@nhost/hasura-auth-js:dev:     at Module.load (node:internal/modules/cjs/loader:1069:32)
@nhost/hasura-auth-js:dev:     at Function.Module._load (node:internal/modules/cjs/loader:904:12)
@nhost/hasura-auth-js:dev:     at Module.require (node:internal/modules/cjs/loader:1093:19)
@nhost/hasura-auth-js:dev:     at require (node:internal/modules/cjs/helpers:108:18)
@nhost/stripe-graphql-js:dev: Error: STRIPE_SECRET_KEY env var is not set
@nhost/stripe-graphql-js:dev:     at Object.<anonymous> (C:\Users\RG\Desktop\projects\nhost\integrations\stripe-graphql-js\src\utils.ts:7:9)
@nhost/stripe-graphql-js:dev:     at Module._compile (node:internal/modules/cjs/loader:1191:14)
@nhost/stripe-graphql-js:dev:     at Module._compile (C:\Users\RG\Desktop\projects\nhost\node_modules\.pnpm\source-map-support@0.5.21\node_modules\source-map-support\source-map-support.js:568:25)
@nhost/stripe-graphql-js:dev:     at Module.m._compile (C:\Users\RG\AppData\Local\Temp\ts-node-dev-hook-20686829275301322.js:69:33)
@nhost/stripe-graphql-js:dev:     at Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
@nhost/stripe-graphql-js:dev:     at require.extensions..jsx.require.extensions..js (C:\Users\RG\AppData\Local\Temp\ts-node-dev-hook-20686829275301322.js:114:20)
@nhost/stripe-graphql-js:dev:     at require.extensions.<computed> (C:\Users\RG\AppData\Local\Temp\ts-node-dev-hook-20686829275301322.js:71:20)
@nhost/stripe-graphql-js:dev:     at Object.nodeDevHook [as .ts] (C:\Users\RG\Desktop\projects\nhost\node_modules\.pnpm\ts-node-dev@2.0.0_vq46kxj6zfka4f6ijsosnft3hy\node_modules\ts-node-dev\lib\hook.js:63:13)
@nhost/stripe-graphql-js:dev:     at Module.load (node:internal/modules/cjs/loader:1069:32)
@nhost/stripe-graphql-js:dev:     at Function.Module._load (node:internal/modules/cjs/loader:904:12)
@nhost/stripe-graphql-js:dev: [ERROR] 12:25:15 Error: STRIPE_SECRET_KEY env var is not set
```

this is my first time on this repo and i am not sure how to proceed 
**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: latest master branch
- node version: 16.19.1

**Comment by szilarddoro** [comment]
Hey @RG7279805! I have two follow-up questions:
 - What version of `pnpm` are you using?
 - Could you please confirm that the config files are really there in the `config` folder?

Also, please try to run `pnpm build` and see what the output of that command is.

**Comment by szilarddoro** [comment]
Because of the lack of additional context, I'm closing this issue. Feel free to reopen if the problem persists.
