### ISSUE TITLE
Issue with 1MB+ file uploads using nhost-js package

### ISSUE THREAD

**Issue by CovenantChurch** [nhost/nhost#210]
When uploading a file below 1MB, I have no issues. Everything works great and I can access the file as expected.
However when I try to upload a file over 1MB, I get  a CORS error and a 413 response. While using "@nhost/nhost-js" version 0.3.6 and "@nhost/react-apollo" version 2.1.0, the 1MB+ files would have a preflight of 29ms and a response time on the upload of 150-200ms. After updating to versions 0.3.7 and 2.1.1, The preflight is still the same (expect) but the upload seems that it's actually attempting the upload but then still responds with a CORS error and 413. For example, a 2.2MB file has a response time ~3.5s and a 6.2MB file is ~9.95s. 

I have confirmed the buckets max upload size is set high enough, I have even tried a bucket with a max upload size of 62.5 MB (500000000 bits) just to make sure that wasn't an issue and I got the same response. The code itself is super basic and again, it does work, just not on files larger than 1MB.

It is a drag and drop file upload that also lets you click to choose a file. It acts the same way for both dropping and choosing a file. 

Update: Not sure if this is helpful but I got the CLI (v0.6.1) working locally and tried file upload and I was able to upload a 14.7 MB file and it worked great. I have also tried manually adding the CORS header it is referring to in the generateUploadHeaders method for the HasuraStorageApi class in the @nhost/hasura-storage-js/dist/index.es.js file but there was no luck there either.

**Comment by CovenantChurch** [comment]
Here is a screenshot of the error details from the network tab of chrome dev tools.
This same error occurs from the hosted site as well, not just localhost.

![Screen Shot 2022-02-22 at 9 23 23 AM](https://user-images.githubusercontent.com/85887071/155151949-63919de8-cb4e-48aa-95ba-f4eed0e0bdd7.png)

**Comment by Svarto** [comment]
@elitan @CovenantChurch I ran into this issue as well when not using nhost-js but uploading directly through the api using axios (I am migrating from nhost v1 to v2). Smaller files get uploaded fine, but anything bigger than 106682 (this is from storage.files in nhost v2 hasura) returns 413 error. This is even when I set the bucket (I am using default bucket) to a lot higher, 1900000000 to be exact.

**Comment by Svarto** [comment]
@elitan Did a bit more testing, locally it works to upload bigger images (I tried 7.2MB and uploaded fine), however the nhost-cli does spit out an error, not sure if it is related but including it here anyway, see bottom.

So to summarize, I have only encountered the error in production, and on my end using the api directly so not only the nhost-js SDK.

```
  throw err;
  ^

Error: Cannot find module '/Users/svarto/WebstormProjects/yumee_mobile/node_modules/express'
Require stack:
- /private/var/folders/_w/90dgmyk553329f8t09bg68mm0000gn/T/807303940/notifications/3233342974.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1065:15)
    at Function.Module._load (internal/modules/cjs/loader.js:911:27)
    at Module.require (internal/modules/cjs/loader.js:1125:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/private/var/folders/_w/90dgmyk553329f8t09bg68mm0000gn/T/807303940/notifications/3233342974.js:2:19)
    at Module._compile (internal/modules/cjs/loader.js:1236:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1257:10)
    at Module.load (internal/modules/cjs/loader.js:1085:32)
    at Function.Module._load (internal/modules/cjs/loader.js:950:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/private/var/folders/_w/90dgmyk553329f8t09bg68mm0000gn/T/807303940/notifications/3233342974.js'
  ]
}
internal/modules/cjs/loader.js:1068
  throw err;
  ^

Error: Cannot find module '/Users/svarto/WebstormProjects/yumee_mobile/node_modules/express'
Require stack:
- /private/var/folders/_w/90dgmyk553329f8t09bg68mm0000gn/T/807303940/cloudfunctions/1478935425.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1065:15)
    at Function.Module._load (internal/modules/cjs/loader.js:911:27)
    at Module.require (internal/modules/cjs/loader.js:1125:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/private/var/folders/_w/90dgmyk553329f8t09bg68mm0000gn/T/807303940/cloudfunctions/1478935425.js:2:19)
    at Module._compile (internal/modules/cjs/loader.js:1236:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1257:10)
    at Module.load (internal/modules/cjs/loader.js:1085:32)
    at Function.Module._load (internal/modules/cjs/loader.js:950:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/private/var/folders/_w/90dgmyk553329f8t09bg68mm0000gn/T/807303940/cloudfunctions/1478935425.js'
  ]
}
```

**Comment by oristian** [comment]
I am seeing this same behavior.  A typical iPhone export could be 4MB - a 1MB limit on storage files in production is not really something we can wait to have fixed.  Can we accelerate the discovery on why this is happening?

**Comment by elitan** [comment]
We've made some updates to our infrastructure and you should be able to upload files up to 500MB now.

I'm closing this issue for now but feel free to ping here if you still have this problem and I'd be happy to re-open.

**Comment by bigzhu** [comment]
Same error happen in my project use hasura-storeage v0.3.3
