### ISSUE TITLE
Custom API - Allow for use of ES6 import 

### ISSUE THREAD

**Issue by wontwon** [nhost/nhost#44]
Environment - Local/Nhost Dev
Machine - Apple M1 Macbook Pro

**Issue** 
When trying to create a custom API, I installed the Twilio package and the nhost_api server crashed and logged the following
```
nhost_api | import net from 'net';

nhost_api | ^^^^^^

nhost_api |

nhost_api | SyntaxError: Cannot use import statement outside a module

nhost_api | at wrapSafe (internal/modules/cjs/loader.js:979:16)

nhost_api | at Module._compile (internal/modules/cjs/loader.js:1027:27)

nhost_api | at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)

nhost_api | at Object.require.extensions.<computed> [as .ts] (/usr/src/app/node_modules/ts-node/src/index.ts:1286:43)

nhost_api | at Module.load (internal/modules/cjs/loader.js:928:32)

nhost_api | at Function.Module._load (internal/modules/cjs/loader.js:769:14)

nhost_api | at Module.require (internal/modules/cjs/loader.js:952:19)

nhost_api | at require (internal/modules/cjs/helpers.js:88:18)

nhost_api | at /usr/src/app/index.ts:17:26

nhost_api | at Array.forEach (<anonymous>)
```

**Expectation**
I should be able to import an npm package without issue

**Comment by wontwon** [comment]
Closing this. It was an error on my behalf not realizing that the node modules needed to exist at the root api directory.
