### ISSUE TITLE
Error using auth with emulator

### ISSUE THREAD

**Issue by hotrush** [nhost/nhost#615]
Hello, trying to signup user using js sdk and nhost emulator but getting an error.

```
import { NhostClient } from '@nhost/nhost-js'

nhost = new NhostClient({
  backendUrl: 'http://localhost:1337'
})

await nhost.auth.signUp({
    email: payload.email,
    password: payload.password,
    options: {
      displayName: payload.name,
      allowedRoles: ['user'],
      defaultRole: 'user'
    }
  })
```

```
utils.js:574 Missing onError handler and/or unhandled exception/promise rejection for invocation 'signUp'. Original error: 'TypeError: adapter is not a function'.  Stacktrace was 'TypeError: adapter is not a function
    at dispatchRequest (chrome-extension://eglmfhjigjnbbfibaaallaoddlloinnc/background.js:3416:10)
    at Axios.request (chrome-extension://eglmfhjigjnbbfibaaallaoddlloinnc/background.js:3103:15)
    at Axios.httpMethod [as post] (chrome-extension://eglmfhjigjnbbfibaaallaoddlloinnc/background.js:3138:19)
    at Function.wrap [as post] (chrome-extension://eglmfhjigjnbbfibaaallaoddlloinnc/background.js:3832:15)
    at postRequest (chrome-extension://eglmfhjigjnbbfibaaallaoddlloinnc/background.js:798:30)
    at signUp (chrome-extension://eglmfhjigjnbbfibaaallaoddlloinnc/background.js:1326:16)
    at Interpreter.exec (chrome-extension://eglmfhjigjnbbfibaaallaoddlloinnc/background.js:12468:98)
    at Interpreter.execute (chrome-extension://eglmfhjigjnbbfibaaallaoddlloinnc/background.js:11805:14)
    at Interpreter.update (chrome-extension://eglmfhjigjnbbfibaaallaoddlloinnc/background.js:11831:12)
    at chrome-extension://eglmfhjigjnbbfibaaallaoddlloinnc/background.js:11711:15' Current error is 'Error: Unable to evaluate guard 'unverified' in transition for event 'error.platform.signUp' in state node 'nhost.authentication.registering':
Cannot read properties of undefined (reading 'status')'. Stacktrace was 'Error: Unable to evaluate guard 'unverified' in transition for event 'error.platform.signUp' in state node 'nhost.authentication.registering':
Cannot read properties of undefined (reading 'status')
    at StateNode.next (chrome-extension://eglmfhjigjnbbfibaaallaoddlloinnc/background.js:9538:17)
    at StateNode.transitionLeafNode (chrome-extension://eglmfhjigjnbbfibaaallaoddlloinnc/background.js:9405:26)
    at StateNode._transition (chrome-extension://eglmfhjigjnbbfibaaallaoddlloinnc/background.js:9498:19)
    at StateNode.transitionParallelNode (chrome-extension://eglmfhjigjnbbfibaaallaoddlloinnc/background.js:9443:33)
    at StateNode._transition (chrome-extension://eglmfhjigjnbbfibaaallaoddlloinnc/background.js:9507:17)
    at StateNode.transition (chrome-extension://eglmfhjigjnbbfibaaallaoddlloinnc/background.js:9769:32)
    at chrome-extension://eglmfhjigjnbbfibaaallaoddlloinnc/background.js:12325:28
    at provide (chrome-extension://eglmfhjigjnbbfibaaallaoddlloinnc/background.js:13340:16)
    at Interpreter.nextState (chrome-extension://eglmfhjigjnbbfibaaallaoddlloinnc/background.js:12324:78)
    at chrome-extension://eglmfhjigjnbbfibaaallaoddlloinnc/background.js:11709:31'
```

Nhost version
```
nhost version  
ℹ Nhost CLI v0.6.10 for darwin-amd64
✔ You have the latest version. Hurray!
```

JS sdk
```
"@nhost/nhost-js": "^1.1.12",
```

**Comment by elitan** [comment]
What's the "emulator" you're referring to?

**Comment by hotrush** [comment]
Sorry, I'm referring to `nhost dev`

**Comment by hotrush** [comment]
So, I think I found the reason. The issue appears because SDK internally uses axios and axios with default config won't work at the service worker because xhr as I understood isn't supported. And it needs to use another adapter e.g. https://www.npmjs.com/package/@vespaiach/axios-fetch-adapter (fetch is supported). So, it would be good to make it possible to pass more config options to `axios.create`...
